screen -S GeversCD -d -m ./examples/Gevers_CDvsNo.sh
screen -S GeversAntibiotics -d -m ./examples/Gevers_AntibioVsNone_DIAGeqYes.sh
screen -S GlobalGutUSvsNon -d -m ./examples/GlobalGut_USvsNon_AgeOver3.sh
screen -S GlobalGutGender -d -m ./examples/GlobalGut_Gender.sh
screen -S HMPSupraSub -d -m ./examples/HMP_SupraVsSubPlaque.sh
screen -S HMPTongeSupra -d -m ./examples/HMP_TongueVsSupraPlaque.sh
screen -S HMPGender -d -m ./examples/HMP_Gender.sh
screen -S SokolCrohns -d -m ./examples/Sokol_HealthyvsChrons.sh
screen -S SokolHealthy -d -m ./examples/Sokol_HealthyvsNot.sh
screen -S SokolColitis -d -m ./examples/Sokol_HealthyvsColitis.sh
