# screen -S GeversCD -d -m ./examples/Gevers_CDvsNo.sh
# screen -S GeversAntibiotics -d -m ./examples/Gevers_AntibioVsNone_DIAGeqYes.sh
# screen -S GlobalGutUSvsNon -d -m ./examples/GlobalGut_USvsNon_AgeOver3.sh
# screen -S GlobalGutSex -d -m ./examples/GlobalGut_Gender.sh
# screen -S GlobalGutGender -d -m ./examples/GlobalGut_Gender.sh
# screen -S HMPSupraSub -d -m ./examples/HMP_SupraVsSubPlaque.sh
# screen -S HMPTongeSupra -d -m ./examples/HMP_TongueVsSupraPlaque.sh
# screen -S HMPGender -d -m ./examples/HMP_Gender.sh
# screen -S SokolCrohns -d -m ./examples/Sokol_HealthyvsCrohns.sh
# screen -S SokolHealthy -d -m ./examples/Sokol_HealthyvsNot.sh
# screen -S SokolColitis -d -m ./examples/Sokol_HealthyvsColitis.sh
 screen -S Bacteremia -d -m ./examples/Bacteremia.sh
# screen -S Cho_Chlortetracycline -d -m ./examples/Cho_Chlortetracycline.sh
# screen -S Cho_Control -d -m ./examples/Cho_Control.sh
# screen -S Cho_Penicillin -d -m ./examples/Cho_Penicillin.sh
# screen -S Cho_VancomycinPenicillin -d -m ./examples/Cho_VancomycinPenicillin.sh
# screen -S Claesson_Age_Class -d -m ./examples/Claesson_Age_Class.sh
# screen -S Claesson_Antibiotics -d -m ./examples/Claesson_Antibiotics.sh
# screen -S Kostic_Normal_vs_Tumor -d -m ./examples/Kostic_Normal_vs_Tumor.sh
